- name: Run bot
        env:
          GATE_API_KEY: ${{ secrets.GATE_API_KEY }}
          GATE_SECRET_KEY: ${{ secrets.GATE_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # ← ganti nama env-nya
        run: python bot.py
